//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealer_Locator.admin.DataExport {
    
    
    public partial class ExportGrouping {
        
        /// <summary>
        /// ExcelDownloadUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.DataExport.ExcelDownload ExcelDownloadUserControl1;
        
        /// <summary>
        /// ExportUnsentLeadsUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.DataExport.ExportUnsentLeads1 ExportUnsentLeadsUserControl1;
    }
}
