//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealer_Locator.admin {
    
    
    public partial class ElectronicDistributionUserControl {
        
        /// <summary>
        /// LocationsControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.Admin.LocationsControl LocationsControl;
        
        /// <summary>
        /// DoNotPlanToBuyControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.Admin.DoNotPlanToBuyControl DoNotPlanToBuyControl;
        
        /// <summary>
        /// RentalAdministratorControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.Admin.RentalAdministratorEmailControl RentalAdministratorControl;
    }
}
