//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealer_Locator.admin.Admin {
    
    
    public partial class ManageCategoriesControl {
        
        /// <summary>
        /// ReorderMainCategoriesControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.Admin.ReorderMainCategoriesControl ReorderMainCategoriesControl;
        
        /// <summary>
        /// SubCategoriesControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.FormDevelopment.SubCategoriesControl SubCategoriesControl;
        
        /// <summary>
        /// ReorderSubCategoriesControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.FormDevelopment.ReOrder.ReorderSubCategoriesControl ReorderSubCategoriesControl;
        
        /// <summary>
        /// MainCategoryDockImageManagerControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.FormDevelopment.MainCategoryDockImageManagerControl MainCategoryDockImageManagerControl;
    }
}
