//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealer_Locator.admin.DataImport {
    
    
    public partial class ImportGrouping {
        
        /// <summary>
        /// ImportDealerInformationUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.DataImport.ImportDealerInformation1 ImportDealerInformationUserControl1;
        
        /// <summary>
        /// ZipCodeImportUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.DataImport.ZipCodeImport ZipCodeImportUserControl1;
    }
}
