//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealer_Locator.admin {
    
    
    public partial class ReportsList {
        
        /// <summary>
        /// PendingLeadsListReportUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.Reports.PendingLeadsListReport PendingLeadsListReportUserControl1;
        
        /// <summary>
        /// GeneralTMReportUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.Reports.GeneralTMReport GeneralTMReportUserControl1;
        
        /// <summary>
        /// BySourceReportUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.Reports.BySourceReport BySourceReportUserControl1;
        
        /// <summary>
        /// ErrorReportsGroupingUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dealer_Locator.admin.Reports.ErrorReportsGrouping ErrorReportsGroupingUserControl1;
    }
}
